import fs from "node:fs";
import path from "node:path";
import { artifacts } from "hardhat";

/** Write the compiled vault ABI to the frontend as a typed `as const` module. */
async function main() {
  const artifact = await artifacts.readArtifact("AutoDcaVault");
  const target = path.resolve(__dirname, "../../nextjs/lib/vaultAbi.ts");
  const body = `// Generated by \`npm run hardhat:abi\`. Do not edit by hand.\nexport const vaultAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  fs.writeFileSync(target, body);
  console.log(`Wrote ${path.relative(process.cwd(), target)} (${artifact.abi.length} entries)`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
